# Generated by Django 6.1.1 on 2026-09-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
